faker-js/faker

README.md, docs/guide/index.md
This might seem a bit unnecessary, but I think it would be a nice quality-of-life addition for the yarn users out there, they can just copy-paste from the doc.
=> docs: add yarn and pnpm install commands

src/internet.ts
Use `datatype.number()` function to generate a number in [src/internet.ts](https://github.com/faker-js/faker/pull/183/files#diff-6ec5c644d528743506612d7d96511ba25dd360836c2139e73d772fe10a25be73), instead of the deprecated `random.number()` function.
=> refactor: Use datatype.number() function instead of random.number()

.github/commit-convention.md
taken from vitejs/vite
closes #190
=> chore: add commit conventions doc

.github/workflows/ci.yml, package-lock.json, package.json, test/finance.unit.js
Fixes #159 
@prisis please review
=> ci: add node version matrix

src/index.ts, src/locales/index.ts
This change is required to allow exporting types from the the locales/index.ts such as `KnownLocale`s.
Prerequisite for https://github.com/faker-js/faker/pull/248
=> feat: use export default for locales

src/locales/en/word/noun.ts
Found during the implementation of https://github.com/faker-js/faker/pull/258
=> fix: jalapeño typo

test/all_functional.spec.ts
This improves the generic tests by adding the locale to the the test description.
Before:
````txt
stdout | test/all_functional.spec.ts > functional tests > random > hexaDecimal()
````
After:
````txt
stdout | test/all_functional.spec.ts > functional tests > en_AU_ocker > random > hexaDecimal()
````
This PR can be reviewed best without showing whitespace changes. (There is a button for  that in the github ui)
=> chore(test): Add locale to test description

src/index.ts, src/locales/index.ts
I will automate the generation/update for `KnownLocale`s in a later PR.
The is the TypeScript related part for https://github.com/faker-js/faker/issues/210
=> feat: add autocomplete support for locales

src/locale/fr_BE.ts, src/locale/lv.ts
This change was originally proposed as part of https://github.com/faker-js/faker/pull/252, but has been extracted to be merged as part of the next release.
=> fix: add missing fakers for existing locales

README.md
The "verb" method on the faker.hacker API is supposed to generate a random hacker verb, not  a random hacker noun.
=> chore(docs): Typo in README

src/word.ts
=> chore: fix JSDoc comments in word.ts

.eslintignore, .gitignore
If someone knows other files that should be ignored, please suggest
=> chore: ignore some more files

src/system.ts
=> chore: fix JSDoc comments in system.ts

src/vehicle.ts
=> chore: fix JSDoc comments in vehicle.ts

scripts/apidoc.ts
The Faker page is currently inaccessible, because it uses the wrong link.
This also uses `.html` suffixes to be more explicit about the file endings.
=> fix: fake docs not accessible

src/datatype.ts, src/helpers.ts, src/name.ts, src/word.ts
=> chore: replace var

.vscode/extensions.json, .vscode/settings.json
=> chore: configure .vscode

docs/.vitepress/theme/index.css, docs/.vitepress/theme/index.mjs, scripts/apidoc.ts
We have to disable processing for parameters as well to avoid issues with potential examples `{{name.first_name}}` in there.
You can test this by adding a js like this:
````ts
* @param format This does some crazy stuff `{{name}}`
````
Example output:
````md
<table>
<thead>
<tr>
<th>Name</th>
<th>Type</th>
<th>Default</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>format?</td>
<td>string</td>
<td></td>
<td>
::: v-pre
This does some crazy stuff `{{name}}`
:::
</td>
</tr>
</tbody>
</table>
````
@Shinigami92 
I decided to use `::: v-pre` (with space) as used in the [official documentation](https://vuepress.vuejs.org/guide/using-vue.html#escaping).
I will split any "omit ::: v-pre if unnecessary"  optimizations into later PRs.
=> docs: use html tables instead of md tables to account for ::: v-pre

src/address.ts, src/animal.ts, src/date.ts, src/finance.ts, src/helpers.ts, src/internet.ts, src/lorem.ts, src/random.ts, src/system.ts
All added type annotations were checked against @types/faker@5.5.9 (most recent version that contains a index.d.ts file)
=> chore: add more type annotations

.eslintrc.js, src/address.ts, src/helpers.ts, src/iban.ts, src/image_providers/unsplash.ts, src/internet.ts, src/lorem.ts, src/mersenne.ts, src/phone.ts, src/random.ts, src/vendor/user-agent.ts
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
=> chore: use explicit-module-boundary-types

.eslintrc.js, scripts/apidoc.ts, src/commerce.ts, src/finance.ts, src/image.ts, src/image_providers/lorempicsum.ts, src/image_providers/lorempixel.ts, src/image_providers/unsplash.ts, src/internet.ts, src/lorem.ts, src/vehicle.ts, src/vendor/mersenne.ts, src/vendor/unique.ts, src/vendor/user-agent.ts, test/database.spec.ts, test/finance.spec.ts, test/finance_iban.spec.ts
Use the recommended state of the rule
https://typescript-eslint.io/rules/restrict-plus-operands/
=> chore: use recommended restrict-plus-operands

.github/workflows/ci.yml
https://docs.cypress.io/guides/getting-started/installing-cypress#Environment-variables
This skippes the install process of Cypress binaries
https://github.com/faker-js/faker/runs/5026306806?check_suite_focus=true#step:5:24
We only need Cypress for E2E docs tests
=> ci: use cypress install binary flag

docs/guide/index.md
If we import `faker` by default import as in the sample, we will get the following error.
```js
import faker from '@faker-js/faker';
const randomName = faker.name.findName(); // Rowan Nikolaus
// when using default import , we need to write like `faker.faker.name.findName()`
```
```shell
// result
const randomName = faker.name.findName();
^
TypeError: Cannot read property 'findName' of undefined
```
This can be avoided by using named import.
=> docs(fix): use named import

src/finance.ts
`faker.finance.iban()` is a valid use of Faker. However in TypeScript you get a type error because the optional `formatted` and `countryCode` args are not marked as optional like in other functions.
Tests are written against the cjs bundle without types so did not catch the error.
=> fix: optional args on faker.finance.iban()

src/database.ts
=> docs: improve database jsdocs

src/date.ts
=> docs: improve date jsdocs

src/definitions/finance.ts, src/finance.ts
=> docs: improve finance jsdocs

src/git.ts
=> docs: improve git jsdocs

src/hacker.ts
=> docs: improve hacker jsdocs

.github/.codecov.yml
https://docs.codecov.com/docs/commit-status
=> ci: configure codecov threshold

src/unique.ts, src/vendor/unique.ts, test/unique.spec.ts
Fixes #456 
**Note:** There is a slight imprecision I couldn't remove.
It is possible to omit the parameters, although the referenced method requires them.
If I fix that, it is no longer possible to omit the empty parameter array.
=> fix: fix unique method types

scripts/apidoc.ts
Fixes #412
This removes the links to the non-existing modules in the docs:
- LoremPicsum
- Lorempixel
- Unsplash
=> docs: remove superfluous links in docs

.gitignore, package.json, scripts/bundle.ts
Our `package.json`s `exports` field seems not to work for any case :thinking: 
This creates a `locale/<locale>.js` file for every locale when bundling for cjs so node/npm versions that does not support the exports field can use these redirects.
At least this should work for now and we can release a 6.0.0 soon
=> build: add redirect aliases for cjs

test/address.spec.ts, test/all_functional.spec.ts, test/company.spec.ts, test/database.spec.ts, test/datatype.spec.ts, test/finance.spec.ts, test/git.spec.ts, test/hacker.spec.ts, test/helpers.spec.ts, test/internet.spec.ts, test/lorem.spec.ts, test/mersenne.spec.ts, test/music.spec.ts, test/name.spec.ts, test/random.spec.ts, test/time.spec.ts, test/unique.spec.ts, test/vehicle.spec.ts, test/word.spec.ts
I used regex replacement in VSCode
```
expect\(typeof (.+)\).toBe\('(.+)'\);
->
expect($1).toBeTypeOf('$2');
```
In a second step I replaced all missing manually
---
The benefit is, that it produces a more readable, consistent and specific use case message when the runner fails with it
=> test: use toBeTypeOf

src/datatype.ts, src/date.ts, src/finance.ts, src/helpers.ts, src/image.ts, src/index.ts, src/internet.ts, src/lorem.ts, src/mersenne.ts, src/name.ts, src/phone.ts, src/random.ts, src/time.ts, src/word.ts
Ref: #203 , #514 
I found various issues in the docs that I would like to address.
Mostly this is some minor stuff like a missing dot.
=> docs: various fixes

docs/.vitepress/components/api-docs/method.ts, docs/.vitepress/components/api-docs/method.vue, scripts/apidoc.ts
Fixes #516 
This PR adds a deprecation warning and `See Also` links.
=> docs: show deprecation warnings in api docs

README.md
Related to issue #464
Add simple description for mandatory options in `tsconfig` file of a typescript project.
=> docs: Add prerequisite for typescript configuration

src/mersenne.ts, src/vendor/mersenne.ts
Created in relation to #280.
Converted `MersenneTwister19937` function to a js class declaration.
Things I want to change but need approval:
- proper camelcase for all methods and variables/properties
- remove the file scoped variable `dbg` in line 54 since it is not used anywhere
- property jsdocs for public methods
=> refactor: convert mersenne into a class

scripts/apidoc/apiDocsWriter.ts
This removes the edit links that do not work.
This adds a toc to the page.
I checked that the last section is not missing like when generated by `[[toc]]`.
**Note:**
Merge after #564
=> docs: add toc and hide edit link

src/faker.ts, src/time.ts
=> fix: fix time.recent method signature

CHANGELOG.md, package.json
Interestingly it created a `.0` instead of `.1`, but if this is the schema I'm okay with it :shrug:
=> chore(release): 6.0.0-beta.0

scripts/apidoc/signature.ts
Displays the nested options when used as union:
**Old:**
**New:**
This is now possible thanks to:
https://github.com/TypeStrong/typedoc/issues/1876
=> docs: show union options parameters

scripts/apidoc/directMethods.ts, scripts/apidoc/moduleMethods.ts, src/random.ts
Fixes #592 
<details>
<summary><strong>Diff</strong></summary>
**Old:**
**New:**
</details>
=> docs: display correct signature

src/mersenne.ts, test/mersenne.spec.ts
=> fix: mersenne rand invalid input argument

src/finance.ts
Created in relation to #375
The original issue only stated code for the following `if` statement:
```typescript
if (provider in localeFormat) {
formats = localeFormat[provider]; // there could be multiple formats
if (typeof formats === 'string') {
format = formats;
} else {
format = this.faker.random.arrayElement(formats);
}
}
```  
I also found, that the last `else` statement:
```typescript
else {
// Choose a random provider
// TODO ST-DDT 2022-01-30: #375 This is impossible to access
if (typeof localeFormat === 'string') {
format = localeFormat;
} else if (typeof localeFormat === 'object') {
// Credit cards are in a object structure
formats = this.faker.random.objectElement(localeFormat, 'value'); // There could be multiple formats
if (typeof formats === 'string') {
format = formats;
} …
```
=> fix: remove unreachable code finance

.github/.codecov.yml, src/fake.ts
The threshold is not useful as it only fails PRs that are successfully but the threshold is not meet.
=> ci: configure codecov patch threshold

docs/.vitepress/config.mjs
I used https://github.com/kevcodez/intheloop/issues/2 as a hint which names are probably correct.
Spec: https://wiki.selfhtml.org/wiki/HTML/Elemente/meta
<details>
<summary><strong>Old (Prod)</strong></summary>
</details>
<details>
<summary><strong>Old (Dev)</strong></summary>
</details>
<details>
<summary><strong>New</strong></summary>
</details>
What about the other tags mentioned in the issue?
=> docs: fix page meta

src/iban.ts, test/finance_iban.spec.ts
Fixes #643 by correcting the Costa Rican IBAN formatting
=> fix: corrected the Costa Rican IBAN format

.github/.codecov.yml
this should accommodate refactor PRs that increase uncovered lines
=> ci: reduce diff coverage target

src/fake.ts, test/fake.spec.ts
Fake should behave exactly like the methods being called directly.
That is if the called method returns an empty string, then fake should do the same (and not fail like it does right now).
=> fix: fake is unable to return empty strings

src/datatype.ts, test/datatype.spec.ts
Fixes #334 
`new Date().setFullYear(...)` does not return a consistent value, as the actual time is not fixed an thus depends on the execution time + timezone. 
This PR uses UTC based static values instead.
=> fix: datatype.datetime should use static boundaries

src/datatype.ts, src/faker.ts, src/random.ts, test/faker.spec.ts
Instead of abusing two constructors to call a method, we could just call the method directly.
=> refactor: set seed directly

test/commerce.spec.ts, test/finance.spec.ts
It is expected to get strings in this situations due to fixed precisions for e.g. prices
=> test: remove todo for number conversion

src/date.ts, test/date.spec.ts
Reopen of #576 in favor of cleaner git history.
Created in relation to https://github.com/faker-js/faker/issues/394.
I changed the way dates are created from the `Date.parse` method to the `Date.constructor` since it uses that under the hood ([MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#parameters)). 
Invalid dates were not handled before.
=> refactor: date accept number input

src/image.ts
Related to #556 
After a little study of the topic, I went the easiest way and just replaced the links with placeimg.com on loremflickr.com
At least it will work a little more correctly as possible.
=> fix: replaced placeimg.com on loremflickr.com

src/fake.ts
Created to clarify the usage recommendations of `faker.fake()`:
https://discord.com/channels/929487054990110771/957954416286261288
=> docs: mention template literals in fake docs

src/git.ts, src/lorem.ts, src/random.ts, src/system.ts
String templates would be faster, but also come with proper type checks and easier refactoring.
=> refactor: drop usage of `fake` for internal calls

test/all_functional.spec.ts
The `all_functional.spec.ts` doesn't work as expected. We need to fix this eventually.
This conceals 20 errors:
````txt
FAIL  test/all_functional.spec.ts > functional tests > az > address > state()
FAIL  test/all_functional.spec.ts > functional tests > az > company > companySuffix()
FAIL  test/all_functional.spec.ts > functional tests > az > name > prefix()
FAIL  test/all_functional.spec.ts > functional tests > az > name > suffix()
FAIL  test/all_functional.spec.ts > functional tests > cz > address > state()
FAIL  test/all_functional.spec.ts > functional tests > cz > address > stateAbbr()
FAIL  test/all_functional.spec.ts > functional tests > id_ID > name > prefix()
FAIL  test/all_functional.spec.ts > functional tests > it > name > suffix()
FAIL  test/all_functional.spec.ts > functional …
```
=> test: fix all_functional tests

src/vehicle.ts, test/vehicle.spec.ts
=> fix: Vehicle vin is always 17 characters long

src/fake.ts, test/fake.spec.ts
Fixes the issue described here: https://github.com/faker-js/faker/pull/503#issuecomment-1079744428
=> fix: fake behavior with special replacement patterns

src/fake.ts
Follow up for https://github.com/faker-js/faker/pull/701#pullrequestreview-923418090
=> docs: update faker.fake documentation

scripts/apidoc/parameterDefaults.ts
GitHub showed this at the top and it bothered me, that my code has a warning 😉 .
After this there are 71 lint warnings left in the code.
=> docs: fix lint warning

README.md
I felt that this example is missing somehow if we have examples for other envs...
=> docs: add ts import example in readme

src/commerce.ts
Removed some 'dead' code according to https://github.com/faker-js/faker/issues/690
=> chore: removed outcommented dead code in commerce.ts

src/address.ts
=> refactor(address): drop local references of faker modules

package.json
=> chore: downgrade min npm version from 7 to 6

src/faker.ts
Before we set `this.locale` it is undefined, so there is no need to use it as a fallback.
=> chore: remove useless fallback to undefined

src/name.ts, test/name.spec.ts
=> chore: deprecate name.title() in favor of name.jobTitle()

src/internet.ts
The defaults in the password method are inconsistent, I consolidated them and removed useless lines.
=> refactor: remove inconsistent defaults from internet.password()

src/lorem.ts, test/lorem.spec.ts
As an alternative, we could use the current system `EOL` (or just `\n`).
Ref: #541
=> fix: use `\n` as default separator for lorem.paragraphs()

src/faker.ts
All of our default modules should be readonly (or none).
=> refactor: readonly default modules

test/address.spec.ts, test/commerce.spec.ts, test/company.spec.ts, test/datatype.spec.ts, test/fake.spec.ts, test/finance.spec.ts, test/finance_iban.spec.ts, test/git.spec.ts, test/hacker.spec.ts, test/helpers.spec.ts, test/internet.spec.ts, test/lorem.spec.ts, test/name.spec.ts, test/phone.spec.ts, test/random.spec.ts, test/system.spec.ts, test/vehicle.spec.ts
Waiting on https://github.com/vitest-dev/vitest/pull/1172
Theoretically we would also need that `greaterThanOrEquals` behave the same as `toBeGreaterThanOrEquals`
The one use `number | bigint` and the other uses `number | Date`
=> test: use consistent assertion functions

src/git.ts, test/git.spec.ts
=> feat: configure eol character for git.commitEntry

src/word.ts
Refactor shared logic in the word module in a separate function.
Designed in #589.
=> refactor(word): extract wordlist filter in separate method

src/address.ts, test/address.spec.ts
=> fix: address.nearbyGPSCoordinate

src/finance.ts, src/helpers.ts, src/random.ts, test/helpers.spec.ts, test/random.spec.ts
Created in relation to #492.
Thinks I have done:
- Create and implement 2 new methods `faker.random.objectValue` and `faker.random.objectKey`
- Wrote documentation for both methods
- Wrote test for both methods
- Added a deprecation flag and log for `faker.random.objectElement`
=> feat: separate methods for object key value

src/definitions/finance.ts, src/finance.ts, test/finance.spec.ts
Adds method for randomly selecting a credit card provider from the keys of `faker.definitions.finance.credit_card`
> faker.finance.creditCardProvider()
'visa'
> faker.finance.creditCardProvider()
'diners_club'
For pull request #882
=> feat: add creditCardIssuer

src/faker.ts, test/address.spec.ts, test/animal.spec.ts, test/commerce.spec.ts, test/company.spec.ts, test/database.spec.ts, test/datatype.spec.ts, test/date.spec.ts, test/faker.spec.ts, test/finance.spec.ts, test/finance_iban.spec.ts, test/git.spec.ts, test/hacker.spec.ts, test/helpers.spec.ts, test/internet.spec.ts, test/lorem.spec.ts, test/music.spec.ts, test/name.spec.ts, test/phone.spec.ts, test/random.spec.ts, test/system.spec.ts, test/time.spec.ts, test/unique.spec.ts, test/vehicle.spec.ts, test/word.spec.ts
Via #851 we found out that it is not possible to access the initial seed ⚠️ 
This is a huge bug in my opinion as that way it's not possible to rerun a script with that seed
=> feat: return seed value from seed()

src/address.ts, src/animal.ts, src/commerce.ts, src/company.ts, src/database.ts, src/datatype.ts, src/date.ts, src/fake.ts, src/finance.ts, src/git.ts, src/hacker.ts, src/helpers.ts, src/image.ts, src/image_providers/lorempixel.ts, src/internet.ts, src/lorem.ts, src/music.ts, src/name.ts, src/phone.ts, src/random.ts, src/system.ts, src/utils/user-agent.ts, src/vehicle.ts, src/word.ts, test/helpers.spec.ts, test/internet.spec.ts
After we discussed stuff in https://github.com/faker-js/faker/pull/874#issuecomment-1110198059 I move these into helpers
=> refactor: move some random methods to helpers

src/random.ts, test/fake.spec.ts, test/unique.spec.ts
=> fix: replace deprecated arrayElement calls

src/datatype.ts
Discovered in #908
<details>
<summary><strong>Preview (Click to expand)</strong></summary>
</details>
=> chore: add examples and improve jsdocs for datatype.datetime

scripts/bundle.ts
Fully remove support for node v12
For upgrade to node v18 see #847
=> build!: remove node v12 support

src/definitions/definitions.ts, src/definitions/index.ts, src/index.ts
Missed during my previous cleanup.
=> chore: remove obsolete DefinitionTypes type

src/modules/random/index.ts, test/random.spec.ts
Following PRs need to be merged before this PR:
- #790
- #797 
---
I would love to even type the non-array version, but sadly we still have not RegexTypes (https://github.com/microsoft/TypeScript/issues/41160) in TS and we are limited (https://stackoverflow.com/questions/66294091/how-to-create-a-type-that-describes-string-with-only-digits)
=> feat: allow banned as string

src/modules/mersenne/index.ts
although mersenne automatically swap the value if min is bigger than max, but it's a good practice to clear out the confusion.
Fix #775
=> docs: fix mersenne rand min max confusion

package.json
This reverts commit 73db3a77d95a21e320888228e39ebbf60d551451.
=> fix: revert type exports for module NodeNext, Node16 (#979)

package.json
Fix #1004
Recreating https://github.com/faker-js/faker/pull/979 (without changing the base `"types"` field)
=> fix(typescript): support module Node16/NodeNext

.github/workflows/ci.yml
- https://github.com/pnpm/action-setup/issues/47
- https://github.com/pnpm/action-setup/pull/46
- https://github.com/vitejs/vite/pull/8375
=> ci: update to pnpm/action-setup@v2.2.2

src/modules/image/index.ts
When using https for you testpage you can only use the imageUrl function, all the other image  helper functions will generate http:// urls.
This results in the image being blocked by the browser:
```
Mixed Content: The page at 'https://domain.tld/storybook/' was loaded over HTTPS,
but requested an insecure image 'http://loremflickr.com/100/100/nightlife?w=200&fm=webp&q=85'. 
This request has been blocked; the content must be served over HTTPS.
```
https image urls also work when the the page is hosted on http, in fact the http image urls will be redirected to https by lorumflicker.
This PR changes the default to `https://` and because the image is served over https anyway i've removed the `https?: boolean` parameter instead of swapping the default value.
The only code change is in the …
=> feat: always use https for loremflickr

src/modules/image/providers/lorempixel.ts, test/image.spec.ts
Listed as a todo in #1044 
Deprecates `lorempixel.avatar()` in favor of `internet.avatar()`
=> chore(lorempixel.avatar): deprecate

src/modules/fake/index.ts, src/modules/phone/index.ts, test/fake.spec.ts, test/phone.spec.ts
Listed as a todo in #1044.
This PR does the following things:
- move the implementation from `phone.phoneNumber()` into a new function called `phone.number()`
- deprecate `phone.phoneNumber()` via the internal deprecated method
- add a `@deprecated` JSDoc parameter to the `phone.phoneNumber()` signature documentation
- duplicates the test checks from `phoneNumber()` to `number()`
- add a test case for `phoneNumber()` deprecation log
=> refactor(phone): rename phoneNumber to number

.github/workflows/ci.yml, scripts/bundle.ts, tsconfig.json
This PR  would fix #1073 and target es2019 instead of dropping support for Webpack 4 (which I don't think we should do -- a lot of users are still stuck on Webpack 4, despite how long it has been out).
We're mainly having issues because we use nullish coalescing internally. This requires a target of es2019 instead of es2020. https://esbuild.github.io/content-types/#javascript
Also would fix https://github.com/cypress-io/cypress/issues/21874
=> fix: lower target to support Webpack 4

src/modules/random/index.ts
Is listed in #1044.
But, this comment seems to be outdated.
=> chore(random.alpha): remove todo comment

test/internet.spec.ts
Added more specific regexes to test email and username creation 
Re: #1044
=> chore: testing unpredictable emails and usernames

.eslintrc.js
Since we have no warnings for the `jsdoc/sort-tags` eslint rule anymore I promoted its mode from `'warning'` to `'error'` as stated in the comment above.
=> chore(linter): set 'jsdoc/sort-tags' rule to 'error'

src/modules/company/index.ts
Hello guys. I added deprecated workflow to parameter of `company.name`.
I hope that I have contribute correctly 😀
=> refactor(company.name): deprecate `format` parameter

test/scripts/apidoc/examplesAndDeprecations.spec.ts
Checks that all `@see faker` method references to contain `(...)`.
**Invalid:**  `@see faker.helpers.arrayElement`
**Valid:**  `@see faker.helpers.arrayElement()`
Note: I'm not sure whether empty `()` are the correct way to have. Especially, if the method requires parameters.
=> test: validate @see contents

src/modules/address/index.ts
As discussed in a previous team meeting. We won't support string coordinates in the long run, so it doesn't make sense to allow it as input parameter either.
Suggested workaround: The user should use type coercion if necessary while passing the parameters.
=> chore(address): remove obsolete TODO

test/internet.spec.ts
Found in #1059. 
The implementation of `internet.username()` uses the provided first and last name and can append a random number to them. This number is between 0 and 99 (inclusive). 
https://github.com/faker-js/faker/blob/93ef876e54886c2b13afda2e69e1b656dbbdc1f0/src/modules/internet/index.ts#L142-L145
The test on the other hand side uses a regex that expects the email to have a number (if existing) that has at least a length of 2.
This PR fixes the described issue.
=> test(internet): fix username expecting numbers with length 2

src/modules/name/index.ts, test/__snapshots__/name.spec.ts.snap, test/name.spec.ts
Requested by @ST-DDT via https://github.com/faker-js/faker/issues/776#issuecomment-1220384286
This function is just a helper for users that want to use faker instead of plain TS
=> feat(name): add sexType method

src/modules/helpers/index.ts
This PR deprecates `faker.helpers.repeatString()` in favor of the native supported [String.prototype.repeat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat).
=> refactor(helpers): deprecate repeatString

.github/renovate.json5
This PR changes the interval from "at any time" to a weekly basis every Monday morning via a [cron](https://crontab.guru/crontab.5.html) expression. 
Important reference links:
- [Renovate schedule config](https://docs.renovatebot.com/configuration-options/#schedule)
- [Cron expression descriptor (for cron expression validation)](https://crontab.cronhub.io/)
=> infra: set renovate schedule to weekly

src/modules/color/index.ts, src/modules/database/index.ts, src/modules/datatype/index.ts, src/modules/finance/index.ts, src/modules/git/index.ts, test/__snapshots__/datatype.spec.ts.snap, test/datatype.spec.ts
This PR resolves a BREAKING CHANGE introduced in #1238.
=> fix(datatype): unintentional hex breaking change

src/modules/datatype/index.ts
Fix errant jsdoc to account for the default `prefix` now being `0x`
=> docs(datatype): fix hexadecimal jsdoc

src/internal/deprecated.ts
Remove duplicate dot at EOL.
````diff
- [@faker-js/faker]: faker.image.lorempicsum.avatar() is deprecated since v7.3 and will be removed in v8.0. Please use faker.internet.avatar() instead..
+ [@faker-js/faker]: faker.image.lorempicsum.avatar() is deprecated since v7.3 and will be removed in v8.0. Please use faker.internet.avatar() instead.
````
=> fix(internal): Fix typo in deprecation message

test/__snapshots__/datatype.spec.ts.snap
=> chore: remove obsolete test snapshots

scripts/apidoc/moduleMethods.ts, src/faker.ts, src/index.ts, src/modules/address/index.ts, src/modules/animal/index.ts, src/modules/color/index.ts, src/modules/commerce/index.ts, src/modules/company/index.ts, src/modules/database/index.ts, src/modules/datatype/index.ts, src/modules/date/index.ts, src/modules/fake/index.ts, src/modules/finance/index.ts, src/modules/git/index.ts, src/modules/hacker/index.ts, src/modules/helpers/index.ts, src/modules/image/index.ts, src/modules/internet/index.ts, src/modules/lorem/index.ts, src/modules/mersenne/index.ts, src/modules/music/index.ts, src/modules/name/index.ts, src/modules/phone/index.ts, src/modules/random/index.ts, src/modules/science/index.ts, src/modules/system/index.ts, src/modules/unique/index.ts, src/modules/vehicle/index.ts, src/modules/word/index.ts, test/mersenne.spec.ts
=> feat(modules): export module interfaces

src/modules/mersenne/index.ts
closes https://github.com/faker-js/faker/issues/1333
=> fix: improve default seed initialization

.github/workflows/ci.yml, .github/workflows/semantic-pull-request.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> ci: workflows security hardening

src/locales/en/finance/currency.ts
I updated the code and symbol according to wikipedia. 
See https://en.wikipedia.org/wiki/Belarusian_rubel#Third_rubel,_2016%E2%80%93present
=> fix(finance): Update Belarusian Ruble to new version

src/locales/en/finance/currency.ts
See https://github.com/faker-js/faker/pull/1392#discussion_r980168548
=> fix(finance): fix typo in Belarusian Ruble's name

src/locales/id_ID/name/male_first_name.ts
I saw that we are missing starts with Z for male first name, but actually there is
It is Zaki, Zakir, and Zulfikar, it is commonly used for millenials muslims male first name.
There's more, but I probably would added these 3 because it is the most common used.
=> feat(locale): add male first names starting with Z to id_ID

src/faker.ts, src/modules/mersenne/index.ts
Marks the Mersenne Module as deprecated, because it will be an internal module in the future.
Preparatory work for #1348 .
=> chore: mark mersenne as deprecated (internal)

test/locales.spec.ts
=> test: fix lint warning and simplify locales test
