README.md

This might seem small, but it's against convention and a little bit of an OCD thing for me.

docs: minor capitalization fix

---

README.md
docs/api/localization.md

This change was originally proposed as part of https://github.com/faker-js/faker/pull/252, but has been extracted to be potentially merged as part of the next release.

docs: update locale list/table in docs

---

src/time.ts

chore: fix JSDoc comments in time.ts

---

docs/.vitepress/config.mjs

I think this would help get more people into the Discord server and facilitate a better community.

chore: add discord link to fakerjs.dev navbar

---

src/name.ts

fix: param can be optional

---

README.md
docs/.vitepress/config.mjs
netlify.toml

chore: StackBlitz playground

---

src/image.ts

docs: improve image jsdocs

---

src/mersenne.ts

docs: improve mersenne jsdocs

---

src/unique.ts

docs: improve unique jsdocs

---

src/lorem.ts

docs: improve lorem jsdocs

---

.github/renovate.json5

Group doc dependencies together so we now when we need to test vitepress docs and ensure nothing broke

ci: group doc deps together

---

test/finance.spec.ts

Thanks to a random god (don't know how made that) the finance module was already rewritten :eyes: 
This is "just" a cleanup to bring it in structure like all other tests
Also it now runs all seeded tests inside the for loop

test: cleanup finance test

---

test/random.spec.ts

Created in relation to #513.
- split the failing test case into 2 explicit once
- fixed typo in surrounding test case
- added todo test case

fix: test random.alphaNumeric

---

README.md

The readme file used to say Deno but I feel like using "CDN Demo" seems more fitting.

fix: correcting the readme file

---

docs/.vitepress/config.mjs

Related to #222
Until we receive the algolia api key, the search bar is not working in any way and just confuse people

docs: comment out algolia until search is available

---

test/address.spec.ts

Related to https://github.com/faker-js/faker/pull/595#discussion_r819488477

chore: fix eslint error

---

.eslintrc.js
pnpm-lock.yaml
src/datatype.ts
src/date.ts
src/finance.ts
src/helpers.ts
src/internet.ts
src/lorem.ts
src/mersenne.ts
src/vendor/mersenne.ts
src/word.ts
test/address.spec.ts
test/finance.spec.ts

Related to https://github.com/faker-js/faker/pull/589#discussion_r819427373

chore: configure eqeqeq lint rule

---

scripts/apidoc/signature.ts

<details>
<summary><strong>Old</strong></summary>
</details>
<details>
<summary><strong>New</strong></summary>
</details>
<details>
<summary><strong>Diff</strong></summary>
</details>

docs: extract defaults from the comments if absent otherwise

---

src/random.ts
test/random.spec.ts
test/system.spec.ts

fix: only return word with desirable alpha characters

---

scripts/generateLocales.ts

I would like to have this method to update locales files more easily when needed.

chore: add updateLocaleFileHook to generateLocales

---

test/random.spec.ts

test: fix random alpha and alphaNumeric tests assumptions

---

src/iban.ts

chore: fix finance.iban warnings

---

src/phone.ts
test/phone.spec.ts

feat: phone IMEI

---

test/random.spec.ts

Supersedes #837
Fixes #809
This PR is way easier to review if you omit white-space changes.

test: add seeded tests for random module

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml

chore(deps): update pnpm to v7

---

test/internet.spec.ts

test: improve internet tests

---

package.json
pnpm-lock.yaml

types needed for e.g. bundle script

chore(deps): add glob types

---

src/locales/en/finance/currency.ts

I also added a symbol.
See https://en.wikipedia.org/wiki/Zambian_kwacha

fix(finance): update Zambian Kwacha to new version

---

src/locales/en/finance/currency.ts

See https://en.wikipedia.org/wiki/Venezuelan_bol%C3%ADvar#Sovereign_bol%C3%ADvar

fix(finance): update Venezuelan bolívar name and code

---

BACKERS.md

M is a consonant because there is a constriction (lips) and pressure build up with partial constriction of the vocal tract. It is indeed a voiced consonant, but it is not a vowel.

docs: fix typo in BACKERS.md
